swagger: '2.0'
info:
  title: Signup API
  description: API para registrarse en el sistema
  version: 1.0.0
basePath: /
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
  /signup:
    post:
      tags:
        - Signup
      summary: Crea una cuenta nueva en el sistema
      description: Endpoint para registrar un nuevo usuario en el sistema
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/definitions/SignupData'
        description: Datos necesarios para crear una nueva cuenta
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/LoginResponse'
        '400':
          description: Bad Request
          schema:
            $ref: '#/definitions/Error'
        '401':
          description: Unauthorized
          schema:
            $ref: '#/definitions/Error'
        '500':
          description: Internal Server Error
          schema:
            $ref: '#/definitions/Error'
definitions:
  SignupData:
    type: object
    required:
      - email
      - password
    properties:
      email:
        type: string
        format: email
        description: Correo electrónico del nuevo usuario
      password:
        type: string
        format: password
        description: Contraseña del nuevo usuario
      name:
        type: string
        description: Nombre del nuevo usuario
  LoginResponse:
    type: object
    properties:
      token:
        type: string
        description: Token de acceso para el nuevo usuario
      user:
        $ref: '#/definitions/User'
  User:
    type: object
    properties:
      id:
        type: string
        description: Identificador único del usuario
      email:
        type: string
        format: email
        description: Correo electrónico del usuario
      name:
        type: string
        description: Nombre del usuario
  Error:
    type: object
    properties:
      message:
        type: string
        description: Mensaje de error detallado
