swagger: "2.0"
info:
  title: Objeto de autenticación
  version: "1.0.0"
paths:
  /login:
    post:
      summary: Iniciar sesión
      description: Endpoint para iniciar sesión en la aplicación
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: Credenciales de inicio de sesión
          required: true
          schema:
            $ref: "#/definitions/Body"
      responses:
        "200":
          description: OK
          schema:
            $ref: "#/definitions/Data"
        "400":
          description: Petición incorrecta
        "401":
          description: No autorizado
        "500":
          description: Error del servidor
definitions:
  Body:
    type: object
    properties:
      email:
        type: string
      password:
        type: string
  Data:
    type: object
    properties:
      token:
        type: string
      user:
        $ref: "#/definitions/User"
  User:
    type: object
    properties:
      id:
        type: string
      email:
        type: string
      name:
        type: string
